# -*- coding: utf-8 -*-
"""Palavra_palindroma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESEnYuuWcRvePYcdiOJP-JWYrXHjXFwk
"""

# plv significa "palavra"

print('Bem-vindo ao programa que responde se uma palavra é palíndroma')

# Pergunta ao usuário qual a palavra eele deseja descobrir se é palíndroma
plv_1 = (input('\nDigite a palvra que vc gostaria de saber se é palíndroma: '))

# lower deixa tudo minúsuculo,
# replace substitu uma parte do texto
# Strip tira pontos em branco na frases
plv_2 = plv_1.lower().replace(' ', '').strip()

# Print da palavra escrita e o resultado
print(f'\nA palavra digitada foi: {plv_1}')
print('\nResultado:')

# Utilização do If, identificando se a palavra é ou não um palíndromo
if plv_1 == plv_2[::-1]:
    print(f'A palavra {plv_1} é um palíndromo')
else:
    print(f'A palavra {plv_1} não é um palíndromo')